### ISSUE TITLE
Final case classes are not supported

### ISSUE THREAD

**Issue by omervk** [ExNexu/spray-json-annotation#1]
```
@jsonstrict
final case class Foo(bar: String)
```

This throws a compile error: `Annotation is only supported on case class`

Is this a false positive perchance?

**Comment by ExNexu** [comment]
Hey @omervk, thanks for reporting it! I think it should work on `final case class`es as well. I'm a bit hesitant to modify something declared `final`, but it's during compile time so I think it's alright. I plan to fix this tonight (PST) and release a new version for you!

**Comment by omervk** [comment]
Wow, thanks for the quick response! Looking forward to seeing this fixed :+1:

**Comment by ExNexu** [comment]
Just pushed version `0.6`. It works in my tests and my larger code bases. Let me know if it works for you too.
